// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxtrwhqlzjxbdxspcncj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4dHJ3aHFsemp4YmR4c3BjbmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNjU0MTMsImV4cCI6MjA3Njk0MTQxM30.9vAyOWwiFDMNBFwbGubumz_nRJjLQglRcNo6M9Nz54Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});